### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Felix-44** [Felix-44/Xilef#28]
it doesn't crash or break anything..it just happens, if anyone could figure it out it would be great
the error:
```
(node:7936) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[2].value: This field is required
embeds[0].fields[2].value: This field is required
    at RequestHandler.execute (C:\Users\Mariano\Desktop\bot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (C:\Users\Mariano\Desktop\bot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
(node:7936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```
how to trigger it: unknown

**Comment by Felix-44** [comment]
this bug doesn't seem to appear anymore, unless anyone knows something about it I'll close this issue

**Comment by Felix-44** [comment]
time to close
