### ISSUE TITLE
Bot crashing for missing permissions

### ISSUE THREAD

**Issue by Felix-44** [Felix-44/Xilef#69]
We don't know much but we have to fix it
perhaps we can make an error handler?

**Comment by LJMSU** [comment]
add
```js
.catch((error) => {
  /* handle error */
});
```
after every `message.channel.send()` :trollface:

**Comment by LJMSU** [comment]
no joke
from what I see it must've came from `message.channel.send`
and to catch an error caused by it, you need to .catch it

**Comment by Felix-44** [comment]
there must be a client.on("error") or something?

**Comment by LJMSU** [comment]
Well there is but I don't know if it'll work

**Comment by Felix-44** [comment]
@unholy-codeism could you do some tests in your rework branch?

**Comment by unholy-codeism** [comment]
> @unholy-codeism could you do some tests in your rework branch?

certainly
but what tests exactly?

**Comment by Felix-44** [comment]
> > @unholy-codeism could you do some tests in your rework branch?
> 
> certainly but what tests exactly?

see if client.on("error") (or whatever it's called) can fix these issues
maybe it should redirect the error message in a dm with me?

**Comment by unholy-codeism** [comment]
ok
but before i start testing could you send a detailed error log for posteriority purposes and also for testing in itself

**Comment by Felix-44** [comment]
```
- Command call completed sucessfully:
        Command: hi
        Args: 
        Time taken: 5
        Called at: Sun Dec 19 2021 16:05:24 GMT+0100 (Central European Standard Time)
        Caller: Rilaz4
        Channel name: general
        Guild name: rally's world
/home/container/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:15) {
  method: 'post',
  path: '/channels/920385935810637856/messages',
  code: 50013,
  httpStatus: 403,
  requestData: {
    json: {
      content: 'Hi.',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: 0,
      message_reference: { message_id: '922142584535654430', fail_if_not_exists: true },
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
container@pterodactyl~ Server marked as offline...
```

**Comment by unholy-codeism** [comment]
ok that's interesting

since it's in rally's server could he check the bot's permissions there? i'm pretty sure it's something on his end (although it could very well not be)

**Comment by Rilaz4** [comment]
I believe I found the cause

If you go to a channel's permissions and set Send Messages to disabled(does not matter if done on the xelif role or xelif as a member), it will crash when attempting to send a message in that channel
